// generalReducer.js
import { createSlice } from "@reduxjs/toolkit"

const initialState = {
  menuLists: [],
}

const generalReducer = createSlice({
  name: "counter", // Name of the slice
  initialState, // Initial state of the counter
  reducers: {
    // Reducer functions here
    setMenuLists: (state, action) => {
      state.online = action.payload
    },
  },
})
// Export the action creators generated by createSlice
export const { setMenuLists } = generalReducer.actions

// Export the reducer itself
export default generalReducer.reducer
